### ISSUE TITLE
Enemies can stack on each other when trying to attack the same unit 

### ISSUE THREAD

**Issue by DrkSephy** [chessmasterhong/WaterEmblem#146]
Although @docmarionum1 added more checks to prevent enemy units from doing weird things in their movement, I've come across another (and hopefully the last bug regarding enemy movement). Multiple enemies will stack on each other if they happen to choose the same unit to attack on the same time. The two screenshots below show that the second enemy will attempt to attack the player on the same tile occupied by another enemy. 

![1](https://cloud.githubusercontent.com/assets/1226900/6048919/dae2444e-ac81-11e4-96a0-279f45227b74.png)

![2](https://cloud.githubusercontent.com/assets/1226900/6048918/dae1a5c0-ac81-11e4-81f4-6b35f6b1fc07.png)

The second enemy will indeed be able to attack, and the game proceeds normally. However, when the Player's turn arrives, if the enemies are still stacked on each other, they will be unable to target one for battle.

**Comment by docmarionum1** [comment]
Scheduling to look at this on Saturday.

**Comment by DrkSephy** [comment]
Not quite, but if you put two enemy spawners in a vertical row above the player, and make the player's `killing edge` have 0 attack, you can easily replicate this. We generally don't save changes to maps.

**Comment by DrkSephy** [comment]
After testing the latest changes, I have not found any problems. Closing this issue for now.
