### ISSUE TITLE
Injecting turn counters into entities 

### ISSUE THREAD

**Issue by DrkSephy** [chessmasterhong/WaterEmblem#159]
Since encounter zones might be a bit of a challenge, here is an alternative. When enemies are spawned, it would be great to pass in a `turn` property. Here is how this would affect movement:

* Once the game has reached that specific turn, those enemies will start to move.
* Ideally, we'd like to have it such that an enemy will attack a player if it gets within attacking range (i.e: break the turn counter restriction). 

Out of the above two, implementing the first point would suffice. With proper placement of units, it would work out nicely (since the player can only cover a computable finite distance per turn/average of turns).

**Comment by chessmasterhong** [comment]
To use this new functionality, add a new property to each Enemy Spawner in Weltmeister called `waitUntilTurn` with the value being the turn in which the enemies spawned by the spawner has to wait until they can perform their action. If no such property is assigned in Weltmeister, the spawner will use its default value of `0` (i.e., spawned units will proceed to perform their action as soon as it is their turn).

The turn waiting behavior will cancel if there is an attackable unit within movement range. Once cancelled, or until the turn passes this waiting value, the enemy will not return to their turn skipping behavior until set again manually by code.
