### ISSUE TITLE
Able to create bosses programmatically

### ISSUE THREAD

**Issue by DrkSephy** [chessmasterhong/WaterEmblem#160]
Based on issue #159, it would also be great if we could add the following properties/abilities:

* The ability to spawn a specific entity (i.e: a boss). 
* The ability to inject a property like `neverMoves`, which means that the entity in question will **never** move. This is useful for putting bosses on special tiles, and for setting up `Seize the tile` objectives. 

These two features seem to be add-ons to the `enemySpawner` method.

**Comment by chessmasterhong** [comment]
To clarify: the spawned unit that is set to never move can still attack only if there is an attackable unit within its attack range, correct?

**Comment by DrkSephy** [comment]
That is correct.

**Comment by chessmasterhong** [comment]
Based on the most recent changes addressing this issue:

In regards to task 1:
Place a boss in their own dedicated array inside `enemy_groups_all` inside the Enemy Spawner. Then, in Weltmeister, assign a custom key, `zone`, and its respective value pair, `#`, to an Enemy Spawner, where # should be replaced with the array index in which the boss is stored in `enemy_groups_all`. If no `zone` key is found, the default value, `0`, will be used.

In regards to task 2:
In Weltmeister, assign a custom key, `immovable`, and its respective value pair, `true`, to an Enemy Spawner if you do not want the spawned enemy unit to move (it will still be able to attack). If no `immovable` key is found, the default value, `false`, will be used.
