### ISSUE TITLE
Continuing a suspended game does not restore game back to a playable state

### ISSUE THREAD

**Issue by chessmasterhong** [chessmasterhong/WaterEmblem#166]
Due to the large number changes done to the codebase since the suspend game feature was last updated, suspending the game will not save all data necessary to bring the game back to a playable state upon continuing the suspended game. Some data were were overlooked and were not saved in the game suspending or were not properly loaded during the game continuing process.

**Comment by DrkSephy** [comment]
The game is in a playable state, however I am unable to cycle through units (stats and portrait will be blank). 

![screen shot 2015-02-17 at 5 00 28 pm](https://cloud.githubusercontent.com/assets/1226900/6238138/b8b616ee-b6c6-11e4-90c6-0c9219dd5b88.png)

**Comment by chessmasterhong** [comment]
Commit 12dddfbddbb347fbd4f7263f2f7ae9dd9ec8e683 should fill up most, if not all, remaining save game data, including but not limited to more battle data and global data. The only time this issue will arise again is if any *temporary* properties were missed in the saving process.

**Comment by chessmasterhong** [comment]
When suspending and loading a suspended game, this happens:

![capture2](https://cloud.githubusercontent.com/assets/1214945/6243057/3e6f0b9c-b708-11e4-9c4e-8ab98f3c0c88.JPG)
