### ISSUE TITLE
Seize Button Appears When It Shouldn't

### ISSUE THREAD

**Issue by docmarionum1** [chessmasterhong/WaterEmblem#189]
~~Got to the end of Chapter 1 and I can't seize the castle with Jaffar.  I've suspended/continued the game several times.~~The seize button is appearing even though it's not the objective.

I'm on firefox

**Comment by DrkSephy** [comment]
I'll fix this. The way I spawn the seize button is by checking for a hidden "throne" terrain under the tile.
