### ISSUE TITLE
Dead enemies show up on status screen

### ISSUE THREAD

**Issue by DrkSephy** [chessmasterhong/WaterEmblem#191]
Cycling through the status screen will show dead enemies. 

![stat screen](https://cloud.githubusercontent.com/assets/1226900/6280915/e1f9c334-b883-11e4-9a1a-c8b60315d55d.png)

**Comment by chessmasterhong** [comment]
I cannot seem to replicate this issue. Would you care to describe in more detail how you came about this bug or what you were doing just before you found this bug?

**Comment by DrkSephy** [comment]
1. Kill an enemy. 
2. Suspend the game.
3. View the unit stat screen.
4. Cycle through, you'll see an enemy with 0/max hp.
