### ISSUE TITLE
Weapon broke mid-battle, freezing game

### ISSUE THREAD

**Issue by DrkSephy** [chessmasterhong/WaterEmblem#195]
I believe my weapon broke mid-battle, causing the errors below:

![screen shot 2015-02-20 at 12 42 49 pm](https://cloud.githubusercontent.com/assets/1226900/6306068/2aec4024-b8fe-11e4-8a0d-649f05c2a95e.png)

**Comment by chessmasterhong** [comment]
What should the intended scenario be if a weapon breaks in mid-battle animation?

**Comment by DrkSephy** [comment]
If a weapon breaks mid-battle animation, the following should happen:

1. Since the game will freeze mid-animation if a weapon breaks, perhaps we should hold off on breaking the weapon until after the animations are finished? 

2. We might need extra checks on queueing up attacks. If the player would attack twice, but only has one weapon usage, we'd need a way to make sure we only queue up one attack (or likewise, dequeue an attack). I think ideally at each stage of the battle animation, we only queue an attack if the unit has a weapon equipped (which I believe we have), so this would be the ideal route (check if the attacking unit's weapon has more than 0 uses, instead of checking for `null`). 

I believe this covers the cases for weapon breaking.
