### ISSUE TITLE
Setup director plugin for map transitions 

### ISSUE THREAD

**Issue by DrkSephy** [chessmasterhong/WaterEmblem#64]
In order to add content (new maps), we need a way to transition between levels. Whenever the map objective has been triggered, we'd like to be taken to the next map. To do so, we'd need the assistance of the director.js plugin: https://github.com/boneheadmed/Director.

**Comment by chessmasterhong** [comment]
Resolved from commit 5e8c3581aa4e08583259a853656cb62fbfc52cd9
