### ISSUE TITLE
Experience progress bar after a battle

### ISSUE THREAD

**Issue by DrkSephy** [chessmasterhong/WaterEmblem#68]
After a battle (after all of the animations have run, but before the fade), it would be a great feature to have a progress bar which shows up and indicates the experience gained by the player.

Having this would also pave the way for a visual level up system to be implemented, which is fairly important. While the level up system exists currently, it only outputs to the console, which isn't useful for the player. 

This doesn't have high priority, but if a progress bar could be implemented, I can also implement a system which will occur on level up and have a nice display to show what stats are being increased.

**Comment by DrkSephy** [comment]
This feature can either be implemented in one of two ways:

1. We display the experience gain bar after animations have finished, but before fading out back into the map. 
2. We display the experience gain bar after animations have finished **and** after fading back onto the map, but **before** the next unit can move. 

Note: Enemy units do not gain experience, so there is no need to hook these up. It might make for an interesting feature in the future, though.

**Comment by DrkSephy** [comment]
I went ahead and tested the experience bar, looks great so far. There is only one bug that I have found right now (or perhaps unintended behavior?): the experience bar will not show up if there is a level up. For example, if I gain enough experience to level up, it will just go straight into the level up sequence. We'd like to show the experience bar loop around 100 first, then go into the level up sequence.

**Comment by chessmasterhong** [comment]
This bug is partially correct. The game will display the experience bar and then proceed to display the level up when the player gains enough experience to level up **only** if the player is the active unit (the one initiating the attack). However, if the player is not (the enemy initiated the attack), then the bug occurs. I will look into fixing this.

**Comment by chessmasterhong** [comment]
Similarly to the aforementioned bug, if the enemy initiates the attack, then the experience bar will not display. It will only display if the player initiates the attack.

**Comment by chessmasterhong** [comment]
Both issues were addressed from commit 8da055b4264f4029b1b4a469e2c7663e60ff2d93. The experience bar should display and properly chain with the level up (if the player unit gains enough experience for a level up) regardless of who initiated the attack.

**Comment by chessmasterhong** [comment]
Resolved from pull request #128.
