### ISSUE TITLE
End Turn does not end all player unit turns when there are no enemies

### ISSUE THREAD

**Issue by DrkSephy** [chessmasterhong/WaterEmblem#71]
Currently, the "End Turn" feature (ends all player unit turns, then switches to the enemy turn) does not work as expected when there are no more enemies. 

This can be seen in two different map conditions:

1. Survive for X amount of turns. Generally, the player will wipe out all enemy units before the turn limit, so this is one case where this bug can be noticed.

2. Seize the tile objectives. Once again, players would generally wipe out the map before attempting to seize the tile.

**Comment by chessmasterhong** [comment]
Resolved from commit 99b295c85c9bd7200dff1b7b626dd14bdde79713.
