### ISSUE TITLE
Enemy plays ranged attack animation when attacking from player unit's left tile.

### ISSUE THREAD

**Issue by DrkSephy** [chessmasterhong/WaterEmblem#72]
It seems that there are still some remnants of ranged attacking. The below screenshot shows a dracozombie attempting to attack me adjacently: 

![adjacent](https://cloud.githubusercontent.com/assets/1226900/5633140/63e4e9a0-95a2-11e4-911e-9c7be3dc04e9.png)

However, the battle scene depicts a ranged combat scene. 
![ranged](https://cloud.githubusercontent.com/assets/1226900/5633148/6bd5041a-95a2-11e4-9209-29f0bd73ac87.png)

This could be due to some remnants of ranged attacking being left inside of the code. In order to reproduce this, simply load up the first map, and end your turn. Let the enemy attack you, and it should demonstrate the behavior above.

**Comment by chessmasterhong** [comment]
This issue may have been involuntarily fixed due to resolving issue #71. I held back on addressing this issue since I a feeling that these two issues may have been related. After several testing attempts, I have not been able to replicate this issue anymore. If no one else is able to repeat this scenario again, this issue will be closed.

**Comment by DrkSephy** [comment]
I am still able to repeat it. By ending my turn and letting the enemy come to attack me, the same ranged attacking animation occurs.

**Comment by chessmasterhong** [comment]
Yes, you are right. The issue can still be repeated. However, it seems that this ranged attack animation bug is triggered only if the enemy is attacking from the left side of the player unit's tile (the exact direction as shown in the first screenshot). Any other direction does not seem to trigger this bug. @DrkSephy, can you verify this?

**Comment by DrkSephy** [comment]
You are correct, this only occurs when being attacked from the left side.
