### ISSUE TITLE
Clicking enemy during player's turn locks game in menu.

### ISSUE THREAD

**Issue by chessmasterhong** [chessmasterhong/WaterEmblem#79]
Clicking an enemy unit during the player unit's turn brings up the action menu as if the player unit has moved already when it actually has not moved yet. The major issue is that this menu **cannot** be escaped by pressing the escape key when it actually should. The only workaround if this scenario occurs is to click on a player unit first (no visuals will happen yet) and then press the escape key.

**Comment by DrkSephy** [comment]
The best solution to this would be to disable the player from clicking an enemy unit, they can only "select" an enemy by pressing the `shift` key to bring up the enemy stat screen, but that is it.

**Comment by chessmasterhong** [comment]
Resolved from pull request #81.
