### ISSUE TITLE
Player units can stack on top of each other.

### ISSUE THREAD

**Issue by chessmasterhong** [chessmasterhong/WaterEmblem#80]
Currently, player units can stack on top of each other (i.e., two or more player units on one tile) with no notification of invalid movement from the game. In fact, the game even proceeds with displaying the action menu in this scenario.

Ideally, there can only be one unit on each tile upon the unit's turn completion, whether it is a player of enemy unit. In addition, the unit should not be able to perform any action while they are stacked on top of another unit. Currently, there are two suggestions of implementation:

1. Add a check to see if the destination tile is occupied before moving the current unit to the tile. If the destination tile is occupied, deny the unit's movement to the tile and let them pick another tile to move to. *(OR)*
2. Allow the unit free movement (no destination tile check) but instead, remove the action menu display should the current unit stop on top of another unit.

**Comment by DrkSephy** [comment]
In order to stick to the original game's movement mechanism, we should stick with implementation method (1). This also leads to increasing the player's intuition towards playing the game, and makes the most sense.

**Comment by chessmasterhong** [comment]
Resolved from pull request #81.
