### ISSUE TITLE
Enemy phase modal does not display for the proper duration.

### ISSUE THREAD

**Issue by chessmasterhong** [chessmasterhong/WaterEmblem#82]
As indicated in pull request #81 in Update 3, the enemy phase modal does not appear for the proper duration. Instead, it briefly flashes the "Enemy Phase" modal and disappears. The flow of battle still proceeds as normal.

The "Enemy Phase" modal should display for the same amount of time as the "Player Phase" modal before allowing the enemy unit to begin performing their actions.

**Comment by DrkSephy** [comment]
Currently, the phase modals work as expected, however the enemy phase modal will display right before each enemy moves, as opposed to just once per turn. If you test this with multiple enemies, it will display the modal before each enemy moves.

**Comment by chessmasterhong** [comment]
Resolved from pull request #84.
