### ISSUE TITLE
Viewing the unit stats screen subsequent times using the same active player unit on the same turn locks the game in screen.

### ISSUE THREAD

**Issue by chessmasterhong** [chessmasterhong/WaterEmblem#83]
During the player unit's turn, if the player views the unit stats screen (hovering over any unit and pressing the `SHIFT` key) any **subsequent** time and tries to escape (using the `ESCAPE` key), the player is unable to leave the screen, leaving the game in an unplayable state. This occurs only when using the same active player unit and on the same turn. If the active player unit changes or is in a new turn, this issue will not take effect.

An example of when this scenario will most likely occur is when a player repeatedly checks the units on the battlefield on the same turn perhaps due to strategical planning (which can happen quite frequently).

The player should be able to enter and leave the unit stats screen as many times as desired provided that the active unit is a player unit.

**Comment by DrkSephy** [comment]
I just noticed this. However, the player can actually press `ENTER` at any time to escape from this menu, and it works all of the time. I believe that is how I originally programmed it (to exit on pressing enter). It would probably be a better idea to have it always work with escape, though (for consistency's sake).
