### ISSUE TITLE
Incorporate weather effects into the game

### ISSUE THREAD

**Issue by DrkSephy** [chessmasterhong/WaterEmblem#99]
Before maps are built, I was wondering if @chessmasterhong might want to incorporate his ImpactJS Atmosphere plugin for weather effects? If so, I can build maps that would incorporate these elements (lightning, snow, rain, etc).

**Comment by chessmasterhong** [comment]
Sure, the Atmosphere plugin would allow for some interesting maps. In addition to weather effects, we can also utilize day/night scenarios to improve immersion (i.e., launching a surprise attack at night).

The plugin can be found here for future references:
https://github.com/chessmasterhong/impact-atmosphere

**Comment by chessmasterhong** [comment]
The plugin has been added as of commit b0f426f69eb80de4cfc25ade2eb89391a7b23921 but has not been hooked into the game yet. As this is an extra feature, utilizing this plugin will come later once all/most of our primary issues have been addressed.

**Comment by chessmasterhong** [comment]
Added rain to Chapter 2 map and snow to Chapter 4 map in commit 23ede8f33973906d59fa36599698c9c9651e83a7.
